// Generated by build.mjs — edit src/overlay.js and src/i18n.js instead.
;(function () {
/**
 * dsh-annotate — UI message catalog.
 *
 * Deliberately not an ES module: build.mjs prepends this file to the client
 * bundle and wraps it around the injected overlay, and neither is loaded through
 * a module system. Both call `dsaI18n(...)` and get back `{ t, lang, set,
 * toggle, detect }`.
 *
 * Two rules when adding a string:
 *   1. Add the key to BOTH languages below.
 *   2. Call `t('key')` at the use site — never inline a literal.
 * `t` falls back to English and then to the key itself, so a missing
 * translation shows up as a visible key rather than an empty element.
 *
 * Placeholders are `{name}` and are substituted by `t(key, { name: value })`.
 */
function dsaI18n(preferred) {
  var CATALOG = {
    en: {
      // ---- annotation block sent to the model ------------------------------
      'payload.head': '🎯 UI annotations · {page} · viewport {w}×{h} ({count})',
      'payload.selector': '   selector: ',
      'payload.selectorMatches': ' ({count} matches)',
      'payload.semantics': '   semantics: ',
      'payload.component': '   component: ',
      'payload.componentChain': '   component chain: ',
      'payload.geometry': '   position/size: ',
      'payload.viewportZone': ' · viewport {zone} ({x}%W × {y}%H)',
      'payload.styles': '   computed styles: ',
      'payload.text': '   text: ',
      'payload.comment': '   note: ',
      'payload.attached': '{count} attached',
      'payload.removeOne': 'Remove this block from the composer',
      'payload.removeAll': 'Remove all',
      'zone.topLeft': 'top left',
      'zone.topCenter': 'top center',
      'zone.topRight': 'top right',
      'zone.middleLeft': 'middle left',
      'zone.middleCenter': 'center',
      'zone.middleRight': 'middle right',
      'zone.bottomLeft': 'bottom left',
      'zone.bottomCenter': 'bottom center',
      'zone.bottomRight': 'bottom right',

      // ---- injected overlay ------------------------------------------------
      'overlay.saveFailed': 'Annotations cannot be saved in this browser. Attach them to the composer before you navigate away.',
      'overlay.editPin': 'Edit annotation {n}: {comment}',
      'overlay.close': 'Close',
      'overlay.placeholder': 'What should change here? (Shift+Enter for a new line)',
      'overlay.hint': 'Enter to save · Esc to cancel',
      'overlay.save': 'Save',

      // ---- panel: entry points --------------------------------------------
      'panel.headerTitle': 'UI annotations (⌘⇧B): list the local services that are running, open one and annotate it',
      'panel.headerLabel': 'Annotate',
      'panel.headerLabelCount': 'Annotate {count}',
      'panel.tabTitle': 'UI annotations',
      'panel.tabDescription': 'Detect the local web servers that are running, open one, pick elements and send the notes to DeepSeek in one go',
      'panel.noSession': 'Choose a workspace and open a conversation first, then use UI annotations.',
      'panel.language': 'Language',
      'panel.languageSwitch': 'Switch to {lang}',

      // ---- panel: list face -----------------------------------------------
      'list.detecting': 'Scanning for local services…',
      'list.detected': '{count} local services found',
      'list.none': 'No local services found',
      'list.redetect': 'Scan again',
      'list.open': 'Open →',
      'list.emptyHint': 'No local web server is running ({count} ports scanned). Start one, then refresh:',
      'list.copy': 'Copy',
      'list.copied': 'Copied: {text}',
      'list.autoRefresh': 'Checked every 5 seconds. You can also type a port below to open it directly.',
      'list.placeholder': '5173 or localhost:3000',
      'list.addressLabel': 'Local service address',
      'list.openButton': 'Open',
      'list.helpHeader': 'Annotate inside the preview',
      'list.helpPicking': 'Press Mark below, then click an element in the page and write a note. Enter saves it.',
      'list.helpEscape': 'Esc leaves annotation mode. Changing page or scrolling is unaffected — press Mark again whenever you want.',
      'list.helpCmdClick': '⌘/Ctrl+click an element = save it and send immediately.',
      'list.helpSendHeader': 'The list and sending',
      'list.helpSendList': 'The annotations button in the toolbar opens an in-flow list for locating and deleting comments. It never covers the preview.',
      'list.helpSendActions': '“Send annotations” sends only the annotations; “Add to composer” combines them with your draft so you can add context. Annotations survive a failed send.',

      // ---- panel: page face -----------------------------------------------
      'page.back': 'Back',
      'page.forward': 'Forward',
      'page.reload': 'Reload',
      'page.addressPlaceholder': 'Address',
      'page.widthLabel': 'Preview width',
      'page.widthFit': 'Fit',
      'page.widthMobile': 'Mobile',
      'page.listToggleLabel': 'Annotation list, {count}',
      'page.listToggleEmpty': 'Annotation list, empty',
      'page.listExpand': 'Expand the annotation list',
      'page.listCollapse': 'Collapse the annotation list',
      'page.listEmpty': 'No annotations',
      'page.listAria': 'Annotation list',
      'page.backToList': 'Back to the local service list',
      'page.help': 'How this works',
      'page.locate': 'Locate in the preview',
      'page.delete': 'Delete this annotation',
      'page.previewTitle': 'Preview',
      'page.loading': 'Opening the preview…',
      'page.loadingHint': 'Connecting to the local service. Annotations are restored automatically.',
      'page.unavailable': 'Preview unavailable',
      'page.retry': 'Retry',
      'page.markTitle': 'Mark mode: click an element to write a note (Esc to leave)',
      'page.mark': 'Mark',
      'page.marking': 'Marking',
      'page.openExternal': 'Open in the system browser',
      'page.unit': '{count}',
      'page.attach': 'Add to composer',
      'page.send': 'Send annotations',
      'page.sending': 'Sending…',
      'page.sendHint': 'Send only these annotations and keep the composer draft',
      'notice.undo': 'Undo',
      'notice.dismiss': 'Dismiss',
      'notice.deleted': 'Annotation deleted. You can undo this.',
      'notice.badAddress': 'That does not look like an address. Try localhost:5173 or just 5173.',
      'notice.notLocal': 'Open a local development service; external sites and Harness itself are not supported.',
      'notice.previewFailed': 'Could not open the preview',
      'notice.detectFailed': 'Scan failed: {error}',
      'notice.unknownError': 'unknown error',
      'notice.autoOpened': 'One local service found, opened it automatically',
      'notice.storageUnavailable': 'Browser storage is unavailable. Add the annotations to the composer before closing.',
      'notice.finishEditing': 'Save or close the annotation you are editing first.',
      'notice.noComposer': 'Select a conversation with a composer first.',
      'notice.attachFailed': 'Could not add to the composer. The annotations are kept.',
      'notice.attached': 'Added to the composer. Add context and send when ready.',
      'notice.sendUnsupported': 'This Harness build cannot send directly; use “Add to composer”.',
      'notice.notAccepted': 'The conversation did not accept this message',
      'notice.accepted': 'Conversation accepted {count} annotations',
      'notice.sendFailed': 'Send failed, annotations kept: {error}',
      'notice.pluginUnavailable': 'The plugin service is unavailable. Confirm that Harness restarted and loaded the plugin.',
      'notice.loadTimeout': 'The page took too long to load. Check the development service and retry.',
      'notice.draftUnavailable': 'The draft cannot be persisted. Save the annotation first.',
      'notice.elementGone': 'The original element changed or disappeared. The annotation is kept — delete it and annotate again.',
      'host.notLocalTarget': 'Only local development services can be previewed; Harness itself cannot.',
      'host.tooManyPreviews': 'Too many previews are open. Restart the plugin to release the idle ones.',
      'host.noCommand': 'No start command is configured (this is an optional feature).',
      'host.noRoot': 'The workspace directory is unknown, so no dev server can be started.',
      'host.starting': 'A service for this workspace is already starting. Please wait.',
      'host.portBusy': 'That port is already in use and cannot be confirmed as yours. Open it from the local service list, or change the port.',
      'host.startFailed': 'Failed to start: {error}',
      'host.exited': 'The dev server exited ({code})',
      'host.readyTimeout': 'Timed out waiting for the dev server to become ready ({seconds}s)',
      'host.originNotAllowed': 'origin not allowed',
      'host.methodNotAllowed': 'method not allowed',
      'host.upstreamUnreachable': 'The local service is unreachable. Check the service or its HTTPS certificate.',
      'host.previewConnectFailed': 'Preview connection failed',
      'host.connectTimeout': 'Connection timed out',
    },

    zh: {
      // ---- annotation block sent to the model ------------------------------
      'payload.head': '🎯 界面标注 · {page} · 视口 {w}×{h}（{count} 条）',
      'payload.selector': '   选择器: ',
      'payload.selectorMatches': '（命中 {count} 个元素）',
      'payload.semantics': '   语义: ',
      'payload.component': '  组件:',
      'payload.componentChain': '   组件链: ',
      'payload.geometry': '   位置/尺寸: ',
      'payload.viewportZone': ' · 视口 {zone}（{x}%W × {y}%H）',
      'payload.styles': '   当前样式: ',
      'payload.text': '   文本: ',
      'payload.comment': '   批注: ',
      'payload.attached': '已附 {count} 条标注',
      'payload.removeOne': '从输入框移除这段标注',
      'payload.removeAll': '全部移除',
      'zone.topLeft': '左上',
      'zone.topCenter': '上中',
      'zone.topRight': '右上',
      'zone.middleLeft': '左中',
      'zone.middleCenter': '正中',
      'zone.middleRight': '右中',
      'zone.bottomLeft': '左下',
      'zone.bottomCenter': '下中',
      'zone.bottomRight': '右下',

      // ---- injected overlay ------------------------------------------------
      'overlay.saveFailed': '批注无法保存到浏览器，请在离开页面前加入输入框。',
      'overlay.editPin': '编辑批注 {n}：{comment}',
      'overlay.close': '关闭',
      'overlay.placeholder': '写一句要改什么…（Shift+Enter 换行）',
      'overlay.hint': 'Enter 保存 · Esc 取消',
      'overlay.save': '保存',

      // ---- panel: entry points --------------------------------------------
      'panel.headerTitle': '界面标注（⌘⇧B）：列出本地在跑的服务，点开就能标注',
      'panel.headerLabel': '标注',
      'panel.headerLabelCount': '标注 {count}',
      'panel.tabTitle': '界面标注',
      'panel.tabDescription': '检测本地在跑的 web，点开即可圈选元素写批注，一次发给 DeepSeek',
      'panel.noSession': '先选择工作区并打开会话，再使用界面标注。',
      'panel.language': '语言',
      'panel.languageSwitch': '切换到{lang}',

      // ---- panel: list face -----------------------------------------------
      'list.detecting': '正在检测本地服务…',
      'list.detected': '检测到 {count} 个本地服务',
      'list.none': '没有检测到本地服务',
      'list.redetect': '重新检测',
      'list.open': '打开 →',
      'list.emptyHint': '没有正在运行的本地 web（已扫 {count} 个端口）。先把它跑起来，再点刷新：',
      'list.copy': '复制',
      'list.copied': '已复制：{text}',
      'list.autoRefresh': '每 5 秒自动检查一次。也可在下方输入端口直接打开。',
      'list.placeholder': '5173 或 localhost:3000',
      'list.addressLabel': '本地服务地址',
      'list.openButton': '打开',
      'list.helpHeader': '在预览里标注',
      'list.helpPicking': '点下面「标记」，然后点页面里的元素写批注，Enter 保存。',
      'list.helpEscape': 'Esc 退出标注状态（换页面、滚动都不受影响，随时再点「标记」继续）。',
      'list.helpCmdClick': '⌘/Ctrl+点击元素 = 写完立即发送。',
      'list.helpSendHeader': '批注列表与发送',
      'list.helpSendList': '顶部工具栏的「批注」按钮可展开列表，逐条定位或删除，不遮挡预览页面。',
      'list.helpSendActions': '「发送批注」只发送当前批注；「加入输入框」可与草稿一起补充后发送。失败时批注会保留。',

      // ---- panel: page face -----------------------------------------------
      'page.back': '后退',
      'page.forward': '前进',
      'page.reload': '重新载入',
      'page.addressPlaceholder': '地址',
      'page.widthLabel': '预览宽度',
      'page.widthFit': '自适应',
      'page.widthMobile': '移动端',
      'page.listToggleLabel': '批注列表，{count} 条',
      'page.listToggleEmpty': '批注列表，暂无批注',
      'page.listExpand': '展开批注列表',
      'page.listCollapse': '收起批注列表',
      'page.listEmpty': '暂无批注',
      'page.listAria': '批注列表',
      'page.backToList': '回到本地服务列表',
      'page.help': '怎么用',
      'page.locate': '在预览里定位',
      'page.delete': '删除这条标注',
      'page.previewTitle': '预览',
      'page.loading': '正在打开预览…',
      'page.loadingHint': '正在连接本地服务，批注会自动恢复。',
      'page.unavailable': '预览暂时不可用',
      'page.retry': '重试',
      'page.markTitle': '标记模式：点击元素写批注（Esc 退出）',
      'page.mark': '标注',
      'page.marking': '标注中',
      'page.openExternal': '在系统浏览器打开',
      'page.unit': '{count} 条',
      'page.attach': '加入输入框',
      'page.send': '发送批注',
      'page.sending': '发送中…',
      'page.sendHint': '只发送这些批注，保留输入框中的草稿',
      'notice.undo': '撤销',
      'notice.dismiss': '知道了',
      'notice.deleted': '已删除批注，可撤销。',
      'notice.badAddress': '这个地址看不出来是什么，试试 localhost:5173 或直接输 5173',
      'notice.notLocal': '请打开本地开发服务；不支持外部网站或 Harness 自身。',
      'notice.previewFailed': '无法打开预览',
      'notice.detectFailed': '检测失败：{error}',
      'notice.unknownError': '未知错误',
      'notice.autoOpened': '检测到 1 个本地服务，已自动打开',
      'notice.storageUnavailable': '浏览器存储不可用，请在关闭前加入输入框。',
      'notice.finishEditing': '请先保存或关闭正在编辑的批注。',
      'notice.noComposer': '请先选择一个有输入框的会话。',
      'notice.attachFailed': '未能加入输入框，批注已保留。',
      'notice.attached': '已加入输入框，可补充说明后发送。',
      'notice.sendUnsupported': '当前 Harness 不支持直接发送，请使用「加入输入框」。',
      'notice.notAccepted': '会话未接受这条消息',
      'notice.accepted': '会话已接收 {count} 条批注',
      'notice.sendFailed': '发送失败，批注已保留：{error}',
      'notice.pluginUnavailable': '插件服务不可用，请确认 Harness 已重启并加载插件。',
      'notice.loadTimeout': '页面加载超时。请检查开发服务后重试。',
      'notice.draftUnavailable': '草稿无法持久保存，请先保存批注。',
      'notice.elementGone': '原元素已变化或消失，批注仍保留，可删除后重新标注。',
      'host.notLocalTarget': '仅支持本地开发服务，不可预览 Harness 自身。',
      'host.tooManyPreviews': '预览数量已达上限，请重启插件释放闲置预览。',
      'host.noCommand': '未配置启动命令（可选功能）',
      'host.noRoot': '不知道工作区目录，无法启动 dev server',
      'host.starting': '当前工作区的服务正在启动，请稍候。',
      'host.portBusy': '该端口已被占用，无法确认属于当前工作区。请从本地服务列表打开，或更换端口。',
      'host.startFailed': '启动失败: {error}',
      'host.exited': 'dev server 退出（{code}）',
      'host.readyTimeout': '等待 dev server 就绪超时（{seconds}s）',
      'host.originNotAllowed': '来源不被允许',
      'host.methodNotAllowed': '请求方法不被允许',
      'host.upstreamUnreachable': '本地服务无法连接，请检查服务或 HTTPS 证书。',
      'host.previewConnectFailed': '预览连接失败',
      'host.connectTimeout': '连接超时',
    },
  }

  var LABELS = { en: 'EN', zh: '中' }

  /** `zh-Hans-CN` and `zh` both mean Chinese; anything else falls through. */
  function normalize(value) {
    var text = String(value || '').toLowerCase()
    if (text.indexOf('zh') === 0) return 'zh'
    if (text.indexOf('en') === 0) return 'en'
    return ''
  }

  function detect() {
    if (typeof navigator === 'undefined') return 'en'
    var tags = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language]
    for (var i = 0; i < tags.length; i += 1) {
      var match = normalize(tags[i])
      if (match) return match
    }
    return 'en'
  }

  function format(template, vars) {
    return String(template).replace(/\{(\w+)\}/g, function (match, key) {
      return vars && Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match
    })
  }

  var lang = normalize(preferred) || detect()

  return {
    get lang() {
      return lang
    },
    label: function () {
      return LABELS[lang] || lang
    },
    /** Name of the language `toggle()` would switch to, for the button title. */
    nextLabel: function () {
      return LABELS[lang === 'en' ? 'zh' : 'en']
    },
    set: function (next) {
      var match = normalize(next)
      if (match) lang = match
      return lang
    },
    toggle: function () {
      lang = lang === 'zh' ? 'en' : 'zh'
      return lang
    },
    detect: detect,
    /** The raw table for one language. `scripts/check.mjs` uses this to assert
     *  that both languages define exactly the same keys. */
    catalog: function (which) {
      return CATALOG[which] || CATALOG.en
    },
    t: function (key, vars) {
      var table = CATALOG[lang] || CATALOG.en
      var value = table[key] === undefined ? CATALOG.en[key] : table[key]
      if (value === undefined) return key
      return vars ? format(value, vars) : value
    },
  }
}

/**
 * dsh-annotate — injected overlay.
 *
 * Runs INSIDE the previewed app document, on its own loopback preview origin.
 * Owns the picking interaction, the pins and the comment card, and keeps the
 * annotation list in localStorage so a reload does not lose the review. Talks to
 * the panel with postMessage only — the panel never reaches into this document,
 * and this file has no dependency on React, which also makes it testable on its
 * own.
 *
 * Design direction: drafting overlay. Hairline measurement frame with corner
 * ticks, monospace readouts, numbered marker pins, and one warm "marker" accent
 * that cannot be confused with the app's own accent colour.
 */
(function () {
  var CHANNEL = 'dsh-annotate-overlay'
  var HOST = 'dsh-annotate-panel'
  var STORE_PREFIX = 'dsh-annotate:v2:'
  var session = String(window.__DSH_ANNO_SESSION__ || 'standalone')
  var currentPage = location.pathname + location.search + location.hash
  var liveElements = new Map()
  var undo = null
  var MARKER = '#f0a05a'

  if (window.__dshAnnotateReady) return
  window.__dshAnnotateReady = true

  // The panel owns the language preference and pushes changes over postMessage;
  // until it says otherwise, follow the browser. `dsaI18n` is prepended to this
  // file by build.mjs.
  var i18n = dsaI18n((window.__DSH_ANNO__ && window.__DSH_ANNO__.lang) || '')
  var t = function (key, vars) { return i18n.t(key, vars) }

  var state = {
    mode: 'idle', // 'idle' | 'picking' | 'writing'
    hover: null,
    selected: null,
    drafting: null, // { id, selector, ... , comment }
    sendOnCommit: false, // ⌘/Ctrl-click submits the batch right away
    annotations: [],
    anchor: null, // element for the open card
  }

  // ---------------------------------------------------------------- utilities

  function isDark() {
    try {
      var bg = getComputedStyle(document.body).backgroundColor || ''
      var m = bg.match(/rgba?\(([^)]+)\)/)
      if (!m) return true
      var parts = m[1].split(',').map(Number)
      var l = (0.2126 * parts[0] + 0.7152 * parts[1] + 0.0722 * parts[2]) / 255
      var alpha = parts.length > 3 ? parts[3] : 1
      if (alpha < 0.2) return true
      return l < 0.5
    } catch (e) {
      return true
    }
  }

  function css() {
    var dark = isDark()
    var ink = dark ? '#f2f3f5' : '#16181d'
    var muted = dark ? 'rgba(242,243,245,.62)' : 'rgba(22,24,29,.58)'
    var panelBg = dark ? 'rgba(20,22,27,.86)' : 'rgba(252,252,253,.90)'
    var hair = dark ? 'rgba(255,255,255,.16)' : 'rgba(16,18,22,.14)'
    var fieldBg = dark ? 'rgba(255,255,255,.06)' : 'rgba(16,18,22,.04)'
    return [
      // Viewport-fixed: apps often scroll an inner container, where document
      // coordinates never change and absolutely-placed pins would sit still.
      '.dsa-layer{position:fixed;inset:0;width:100%;height:100%;margin:0;padding:0;border:0;overflow:visible;background:transparent;z-index:2147483000;pointer-events:none;',
      'font:12px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:' + ink + '}',
      '.dsa-layer *{box-sizing:border-box}.dsa-layer::backdrop{display:none}',
      '.dsa-mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-variant-numeric:tabular-nums}',
      // capture surface (only while picking) — swallows app clicks
      '.dsa-capture{position:absolute;inset:0;z-index:1;pointer-events:auto;cursor:crosshair}',
      // measurement frame
      '.dsa-frame{position:absolute;z-index:3;pointer-events:none;border:1px solid ' + MARKER + ';',
      'background:color-mix(in srgb,' + MARKER + ' 8%,transparent);transition:opacity .12s ease}',
      '.dsa-frame[data-state="hover"]{border-style:dashed;opacity:.85}',
      '.dsa-frame i{position:absolute;width:7px;height:7px;border:1px solid ' + MARKER + ';background:' + panelBg + '}',
      '.dsa-frame i:nth-child(1){left:-4px;top:-4px}.dsa-frame i:nth-child(2){right:-4px;top:-4px}',
      '.dsa-frame i:nth-child(3){left:-4px;bottom:-4px}.dsa-frame i:nth-child(4){right:-4px;bottom:-4px}',
      // hover readout
      '.dsa-readout{position:absolute;z-index:4;pointer-events:none;display:flex;gap:8px;align-items:center;',
      'padding:3px 7px;border:1px solid ' + hair + ';border-radius:3px;background:' + panelBg + ';',
      'box-shadow:0 6px 20px -12px rgba(0,0,0,.6);white-space:nowrap;max-width:min(560px,80vw);overflow:hidden}',
      '.dsa-readout b{color:' + MARKER + ';font-weight:600}',
      '.dsa-readout span{color:' + muted + '}',
      // pins
      '.dsa-pin{appearance:none;padding:0;min-width:0;min-height:0;max-width:none;max-height:none;display:block;position:absolute;z-index:5;pointer-events:auto;width:20px;height:20px;margin:-10px 0 0 -10px;',
      'border-radius:50%;background:' + MARKER + ';color:#20160c;border:1.5px solid ' + panelBg + ';',
      'font:600 11px/17px ui-monospace,SFMono-Regular,Menlo,monospace;text-align:center;cursor:pointer;',
      'box-shadow:0 2px 10px -2px rgba(0,0,0,.55);transform-origin:center;',
      'animation:dsa-pop .18s cubic-bezier(.2,1.4,.4,1)}',
      '.dsa-pin:hover{transform:scale(1.14)}.dsa-pin[hidden]{display:none!important}.dsa-pin:focus-visible{outline:2px solid '+ink+';outline-offset:3px}.dsa-layer button:focus-visible{outline:2px solid '+MARKER+';outline-offset:2px}',
      '.dsa-pin[data-open="true"]{outline:2px solid color-mix(in srgb,' + MARKER + ' 45%,transparent);outline-offset:2px}',
      '@keyframes dsa-pop{from{transform:scale(.4);opacity:0}to{transform:scale(1);opacity:1}}',
      // comment card
      '.dsa-card{position:absolute;z-index:6;width:min(320px,calc(100vw - 16px));pointer-events:auto;color:' + ink + ';',
      'background:' + panelBg + ';border:1px solid ' + hair + ';border-radius:12px;overflow:hidden;',
      'box-shadow:0 24px 60px -28px rgba(0,0,0,.7);backdrop-filter:blur(18px) saturate(160%);',
      'border-left:3px solid ' + MARKER + ';',
      'animation:dsa-rise .16s ease-out}',
      '@keyframes dsa-rise{from{transform:translateY(4px);opacity:0}to{transform:none;opacity:1}}',
      '.dsa-card header{display:flex;align-items:center;gap:8px;padding:7px 8px 7px 10px;border-bottom:1px solid ' + hair + '}',
      '.dsa-card header .dsa-tag{flex:none;color:' + MARKER + ';font-weight:600}',
      '.dsa-card header .dsa-clip{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:' + muted + '}',
      '.dsa-card header button{all:unset;cursor:pointer;width:20px;height:20px;line-height:18px;text-align:center;border-radius:4px;color:' + muted + '}',
      '.dsa-card header button:hover{background:' + fieldBg + ';color:' + ink + '}',
      '.dsa-card textarea{display:block;width:100%;min-height:62px;max-height:220px;resize:vertical;border:0;outline:none;',
      'padding:9px 10px;background:transparent;color:inherit;font:inherit;font-size:12.5px}',
      '.dsa-card footer{display:flex;align-items:center;gap:8px;padding:6px 8px 8px 10px;border-top:1px solid ' + hair + '}',
      '.dsa-card footer .dsa-hint{flex:1;color:' + muted + ';font-size:10.5px}',
      '.dsa-btn{all:unset;cursor:pointer;padding:4px 10px;border-radius:4px;border:1px solid ' + hair + ';font-size:11.5px}',
      '.dsa-btn:hover{border-color:' + MARKER + ';color:' + MARKER + '}',
      '.dsa-btn.primary{background:' + MARKER + ';border-color:transparent;color:#20160c;font-weight:600}',
      '.dsa-btn.primary:hover{opacity:.88;color:#20160c}',
      '@media(prefers-reduced-motion:reduce){.dsa-layer *{animation:none!important;transition:none!important}}',
    ].join('')
  }

  function esc(value) {
    return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
    })
  }

  function clip(text, max) {
    var t = String(text == null ? '' : text).replace(/\s+/g, ' ').trim()
    return t.length > max ? t.slice(0, max - 1) + '…' : t
  }

  /** Prefer a stable authored hook when the app has one. */
  function testIdOf(el) {
    var attrs = ['data-testid', 'data-test', 'data-test-id', 'data-qa']
    for (var i = 0; i < attrs.length; i++) {
      var value = el.getAttribute && el.getAttribute(attrs[i])
      if (value) return attrs[i] + '=' + value
    }
    return null
  }

  /** Short, stable, human-readable path: body > main > section.hero > button.cta */
  function selectorOf(el) {
    var parts = []
    var node = el
    var guard = 0
    while (node && node.nodeType === 1 && node !== document.documentElement && guard++ < 12) {
      var tag = node.tagName.toLowerCase()
      if (node.id) {
        parts.unshift(tag + '#' + CSS.escape(node.id))
        break
      }
      var cls = (node.getAttribute('class') || '').split(/\s+/).filter(Boolean).slice(0, 2)
      var sameTag = node.parentElement
        ? Array.prototype.filter.call(node.parentElement.children, function (c) {
            return c.tagName === node.tagName
          })
        : []
      var nth = sameTag.length > 1 ? ':nth-of-type(' + (sameTag.indexOf(node) + 1) + ')' : ''
      parts.unshift(tag + (cls.length ? '.' + cls.map(function (value) { return CSS.escape(value) }).join('.') : '') + nth)
      if (parts.length > 5) break
      node = node.parentElement
    }
    return parts.join(' > ')
  }

  /** Component chain (up to three names), when the app runs a dev build. */
  function componentChainOf(el) {
    var chain = []
    try {
      var key = Object.keys(el).filter(function (k) {
        return k.indexOf('__reactFiber$') === 0 || k.indexOf('__reactInternalInstance$') === 0
      })[0]
      if (!key) return chain
      var fiber = el[key]
      var guard = 0
      while (fiber && guard++ < 40 && chain.length < 3) {
        var type = fiber.type
        var name = typeof type === 'function' ? type.displayName || type.name : type && type.displayName
        if (name && !/^[a-z]/.test(name) && chain.indexOf(name) === -1) chain.push(name)
        fiber = fiber.return
      }
    } catch (e) {
      /* dev-only nicety */
    }
    return chain
  }

  /** Where the element sits in the viewport, coarse and readable. */
  function placementOf(rect) {
    var cx = (rect.left + rect.width / 2) / Math.max(1, window.innerWidth)
    var cy = (rect.top + rect.height / 2) / Math.max(1, window.innerHeight)
    var col = cx < 0.34 ? 'Left' : cx > 0.66 ? 'Right' : 'Center'
    var row = cy < 0.34 ? 'Top' : cy > 0.66 ? 'Bottom' : 'Middle'
    return {
      x: Math.round(cx * 100),
      y: Math.round(cy * 100),
      zone: t('zone.' + row.toLowerCase() + col),
    }
  }

  /** How many elements the generated selector actually matches: 1 means the
   *  annotation is unambiguous, >1 or 0 must be told to the agent. */
  function selectorMatches(selector) {
    try {
      return document.querySelectorAll(selector).length
    } catch (e) {
      return -1
    }
  }

  /** Nearest React component name, when the app runs a dev build. */
  function componentOf(el) {
    try {
      var key = Object.keys(el).filter(function (k) {
        return k.indexOf('__reactFiber$') === 0 || k.indexOf('__reactInternalInstance$') === 0
      })[0]
      if (!key) return null
      var fiber = el[key]
      var guard = 0
      while (fiber && guard++ < 24) {
        var type = fiber.type
        var name = typeof type === 'function' ? type.displayName || type.name : type && type.displayName
        if (name && !/^[a-z]/.test(name)) return name
        fiber = fiber.return
      }
    } catch (e) {
      /* dev-only nicety */
    }
    return null
  }

  function stylesOf(el) {
    var out = {}
    try {
      var cs = getComputedStyle(el)
      var keys = ['display', 'position', 'gap', 'padding', 'margin', 'width', 'height',
        'font-size', 'font-weight', 'line-height', 'color', 'background-color', 'border-radius',
        'border-width', 'box-shadow', 'opacity', 'z-index']
      for (var i = 0; i < keys.length; i++) {
        var v = cs.getPropertyValue(keys[i])
        if (v && v !== 'none' && v !== 'normal' && v !== 'auto' && v !== '0px') out[keys[i]] = v
      }
    } catch (e) {
      /* cross-origin would have failed earlier */
    }
    return out
  }

  function detailOf(el) {
    var rect = el.getBoundingClientRect()
    var selector = selectorOf(el)
    var chain = componentChainOf(el)
    return {
      selector: selector,
      selectorMatches: selectorMatches(selector),
      testId: testIdOf(el),
      component: chain[0] || componentOf(el),
      componentChain: chain,
      role: el.getAttribute('role') || el.tagName.toLowerCase(),
      ariaLabel: el.getAttribute('aria-label') || null,
      alt: el.getAttribute('alt') || null,
      name: el.getAttribute('name') || null,
      type: el.getAttribute('type') || null,
      tag: el.tagName.toLowerCase(),
      classes: (el.getAttribute('class') || '').split(/\s+/).filter(Boolean).slice(0, 4),
      text: clip(el.textContent || '', 120),
      rect: { x: Math.round(rect.x), y: Math.round(rect.y), w: Math.round(rect.width), h: Math.round(rect.height) },
      // Pins live in document space: mixing a viewport rect with the scroll
      // offset at render time makes them drift instead of following the element.
      doc: {
        x: Math.round(rect.x + window.scrollX),
        y: Math.round(rect.y + window.scrollY),
        w: Math.round(rect.width),
        h: Math.round(rect.height),
      },
      placement: placementOf(rect),
      page: location.pathname + location.search,
      viewport: { w: window.innerWidth, h: window.innerHeight },
      styles: stylesOf(el),
    }
  }

  // -------------------------------------------------------------- persistence

  function storeKey() {
    return STORE_PREFIX + encodeURIComponent(session) + ':' + currentPage
  }

  function load() {
    try {
      var raw = localStorage.getItem(storeKey())
      var list = raw ? JSON.parse(raw) : []
      return Array.isArray(list) ? list : []
    } catch (e) {
      return []
    }
  }

  function save() {
    try {
      localStorage.setItem(storeKey(), JSON.stringify(state.annotations))
    } catch (e) {
      post('warning', { message: t('overlay.saveFailed') })
    }
  }

  // ------------------------------------------------------------------- render

  var root = document.createElement('div')
  root.className = 'dsa-layer'
  var styleEl = document.createElement('style')
  var capture = document.createElement('div')
  capture.className = 'dsa-capture'
  var pinLayer = document.createElement('div')
  var frame = document.createElement('div')
  frame.className = 'dsa-frame'
  frame.innerHTML = '<i></i><i></i><i></i><i></i>'
  var readout = document.createElement('div')
  readout.className = 'dsa-readout dsa-mono'
  var card = null

  function mount() {
    styleEl.textContent = css()
    root.appendChild(styleEl)
    root.appendChild(pinLayer)
    root.appendChild(frame)
    root.appendChild(readout)
    document.documentElement.appendChild(root)
    // The top layer escapes transformed app roots and their clipping contexts.
    if (typeof root.showPopover === 'function') {
      root.setAttribute('popover', 'manual')
      root.showPopover()
    }
    render()
  }

  function mountCapture() {
    var active = state.mode !== 'idle'
    if (active && capture.parentNode !== root) root.insertBefore(capture, pinLayer)
    if (!active && capture.parentNode === root) root.removeChild(capture)
  }

  /**
   * The capture surface owns the pointer while reviewing, so `event.target` is
   * always the surface itself. Resolve the real element under the cursor by
   * asking the document with our own hit-testing switched off for one call.
   */
  function elementAt(x, y) {
    var previous = capture.style.pointerEvents
    capture.style.pointerEvents = 'none'
    var el = document.elementFromPoint(x, y)
    capture.style.pointerEvents = previous || 'auto'
    if (!el || el === root || root.contains(el)) return null
    return el
  }

  function render() {
    var dark = isDark()
    root.setAttribute('data-dark', dark ? '1' : '0')
    mountCapture()
    renderFrame()
    renderPins()
  }

  function renderFrame() {
    var target = state.selected || state.hover
    if (!target || !target.isConnected || !visibleRect(target)) {
      frame.style.display = 'none'
      readout.style.display = 'none'
      return
    }
    var rect = target.getBoundingClientRect()
    frame.style.display = 'block'
    frame.setAttribute('data-state', state.selected ? 'selected' : 'hover')
    frame.style.left = rect.left + 'px'
    frame.style.top = rect.top + 'px'
    frame.style.width = rect.width + 'px'
    frame.style.height = rect.height + 'px'

    readout.style.display = 'flex'
    readout.innerHTML =
      '<b>' + esc(target.tagName.toLowerCase()) + '</b>' +
      (target.getAttribute('class') ? '<span>.' + esc(clip(target.getAttribute('class'), 28).split(' ')[0]) + '</span>' : '') +
      (componentOf(target) ? '<span>· ' + esc(componentOf(target)) + '</span>' : '') +
      '<span>· ' + Math.round(rect.width) + '×' + Math.round(rect.height) + '</span>'
    var top = rect.top - 26
    // A pin is anchored to the element's top edge, so a readout directly above
    // it would sit on the marker; lift it clear instead of stacking two labels.
    var annotated = state.annotations.some(function (ann) {
      var el = elementFor(ann)
      if (!el || !el.isConnected) return false
      var other = el.getBoundingClientRect()
      return Math.abs(other.left + other.width / 2 - (rect.left + rect.width / 2)) < 2 &&
        Math.abs(other.top - rect.top) < 2
    })
    if (annotated) top -= 24
    var left = Math.max(4, rect.left)
    if (top < 4) {
      // No room above: prefer the element's right side (usually open canvas),
      // and only fall back to below when the right edge is too close too.
      if (window.innerWidth - rect.right > 240) {
        left = rect.right + 8
        top = rect.top - 2
      } else {
        top = rect.bottom + 6
      }
    }
    readout.style.left = left + 'px'
    readout.style.top = top + 'px'
  }

  function anchorCard() {
    if (!card || !state.anchor || !state.anchor.isConnected) return
    var rect = state.anchor.getBoundingClientRect()
    var width = card.offsetWidth || 304
    var height = card.offsetHeight || 168
    var gap = 12
    // Never cover the element being annotated: dock to its right, then left,
    // then below/above — the first side with room wins.
    var left
    if (window.innerWidth - rect.right >= width + gap) left = rect.right + gap
    else if (rect.left >= width + gap) left = rect.left - width - gap
    else left = Math.min(rect.left, window.innerWidth - width - 8)
    var top = rect.top
    if (top + height > window.innerHeight - 8) top = Math.max(8, window.innerHeight - height - 8)
    card.style.left = Math.max(8, left) + 'px'
    card.style.top = Math.max(8, top) + 'px'
  }

  /** Where a pin belongs right now, in viewport coordinates: the element's live
   *  position, so it travels with the page whether the window or an inner
   *  container scrolls. Falls back to the recorded document position. */
  function elementFor(ann) {
    var cached = liveElements.get(ann.id)
    if (cached && cached.isConnected) return cached
    var el = query(ann.selector)
    // Never attach to an arbitrary lookalike after a component disappears: the
    // match has to be the same kind of element, not just the same selector.
    if (!el) return null
    if (ann.tag && el.tagName.toLowerCase() !== String(ann.tag).toLowerCase()) return null
    liveElements.set(ann.id, el)
    return el
  }

  function visibleRect(el) {
    if (!el || !el.isConnected || !el.getClientRects().length) return null
    var rect = el.getBoundingClientRect()
    var bounds = { left: 0, top: 0, right: innerWidth, bottom: innerHeight }
    for (var node = el.parentElement; node && node !== document.documentElement; node = node.parentElement) {
      var style = getComputedStyle(node)
      var box = node.getBoundingClientRect()
      if (/(auto|scroll|hidden|clip)/.test(style.overflowX)) {
        bounds.left = Math.max(bounds.left, box.left)
        bounds.right = Math.min(bounds.right, box.right)
      }
      if (/(auto|scroll|hidden|clip)/.test(style.overflowY)) {
        bounds.top = Math.max(bounds.top, box.top)
        bounds.bottom = Math.min(bounds.bottom, box.bottom)
      }
    }
    if (rect.width <= 0 || rect.height <= 0 || rect.bottom <= bounds.top || rect.top >= bounds.bottom ||
        rect.right <= bounds.left || rect.left >= bounds.right) return null
    return { rect: rect, bounds: bounds }
  }

  function pinAnchor(ann) {
    var visible = visibleRect(elementFor(ann))
    if (!visible) return null
    var rect = visible.rect, bounds = visible.bounds
    // Hide the flag when its edge is clipped; never leave a floating flag on
    // another component, and never fall back to stale absolute coordinates.
    if (rect.top < bounds.top || rect.top >= bounds.bottom) return null
    return { x: Math.max(bounds.left + 10, Math.min(bounds.right - 10, rect.left + rect.width / 2)), y: rect.top }
  }

  /** Scroll/resize path: move the existing pins, don't rebuild them. */
  function positionPins() {
    state.annotations.forEach(function (ann, index) {
      var pin = pinLayer.children[index]
      if (!pin) return
      var anchor = pinAnchor(ann)
      pin.hidden = !anchor
      if (anchor) {
        pin.style.left = anchor.x + 'px'
        pin.style.top = anchor.y + 'px'
      }
    })
    anchorCard()
  }

  function renderPins() {
    pinLayer.innerHTML = ''
    state.annotations.forEach(function (ann, index) {
      var pin = document.createElement('button')
      pin.type = 'button'
      pin.setAttribute('aria-label', t('overlay.editPin', { n: index + 1, comment: ann.comment }))
      pin.className = 'dsa-pin'
      pin.textContent = String(index + 1)
      pin.title = ann.comment
      var anchor = pinAnchor(ann)
      pin.hidden = !anchor
      if (anchor) {
        pin.style.left = anchor.x + 'px'
        pin.style.top = anchor.y + 'px'
      }
      pin.setAttribute('data-open', state.drafting && state.drafting.id === ann.id ? 'true' : 'false')
      pin.addEventListener('click', function (event) {
        event.stopPropagation()
        if (state.busy) return
        var el = elementFor(ann)
        if (!el) {
          post('missing', { id: ann.id })
          return
        }
        var live = detailOf(el)
        openCard(
          { id: ann.id, detail: Object.assign({}, ann, { doc: live.doc, rect: live.rect }), comment: ann.comment, existing: true },
          el
        )
        post('focus', { id: ann.id })
      })
      pinLayer.appendChild(pin)
    })
    anchorCard()
  }

  function query(selector) {
    try {
      var matches = document.querySelectorAll(selector)
      return matches.length === 1 ? matches[0] : null
    } catch (e) {
      return null
    }
  }

  // ------------------------------------------------------------------ card UI

  function closeCard(preserve) {
    if (card && preserve !== true) post('draft', { draft: null })
    if (card && card.parentNode) card.parentNode.removeChild(card)
    card = null
    state.drafting = null
    state.anchor = null
    // Writing is a detour, not a destination: coming back from a card leaves
    // picking armed so the next element is one click away — but a caller that
    // already set another mode (setMode('idle') on Esc) must win.
    if (state.mode === 'writing') state.mode = 'picking'
    state.selected = null
    render()
    post('mode', { mode: state.mode, count: state.annotations.length })
  }

  function openCard(draft, el) {
    closeCard()
    state.drafting = draft
    state.mode = 'writing'
    state.anchor = el
    mountCapture()
    post('mode', { mode: state.mode })
    var label = draft.detail.tag + (draft.detail.classes.length ? '.' + draft.detail.classes[0] : '')
    card = document.createElement('div')
    card.className = 'dsa-card'
    card.innerHTML =
      '<header>' +
      '<span class="dsa-tag dsa-mono">' + esc(label) + '</span>' +
      '<span class="dsa-clip dsa-mono">' + esc(draft.detail.selector) + '</span>' +
      '<button type="button" data-act="close" aria-label="' + esc(t('overlay.close')) + '">✕</button>' +
      '</header>' +
      '<textarea placeholder="' + esc(t('overlay.placeholder')) + '"></textarea>' +
      '<footer>' +
      '<span class="dsa-hint dsa-mono">' + esc(t('overlay.hint')) + '</span>' +
      '<button type="button" class="dsa-btn primary" data-act="save">' + esc(t('overlay.save')) + '</button>' +
      '</footer>'
    var area = card.querySelector('textarea')
    area.value = draft.comment || ''
    area.addEventListener('input', function () { post('draft', { draft: Object.assign({}, draft, { comment: area.value }) }) })
    card.querySelector('[data-act="close"]').addEventListener('click', closeCard)
    card.querySelector('[data-act="save"]').addEventListener('click', commit)
    area.addEventListener('keydown', function (event) {
      if (event.isComposing || event.keyCode === 229) return
      if (event.key === 'Enter' && !event.shiftKey) {
        event.preventDefault()
        commit()
      } else if (event.key === 'Escape') {
        event.preventDefault()
        // Esc means "leave annotation mode"; setMode closes the card for us.
        setMode('idle')
      }
    })
    root.appendChild(card)
    anchorCard()
    setTimeout(function () {
      area.focus()
    }, 10)
    post('drafting', { id: draft.id, selector: draft.detail.selector })
    if (area.value) post('draft', { draft: Object.assign({}, draft, { comment: area.value }) })
  }

  /** Follow the panel's language and re-render. A card that is already open is
   *  rebuilt from the same draft, so nothing typed is lost. */
  function setLang(next) {
    if (!next || i18n.set(next) !== next) return
    renderPins()
    render()
    if (card && state.drafting && state.anchor) {
      var draft = Object.assign({}, state.drafting, { comment: card.querySelector('textarea').value })
      openCard(draft, state.anchor)
    }
  }

  function commit() {
    if (!card || !state.drafting || !state.anchor) return
    var text = card.querySelector('textarea').value.trim()
    if (!text) {
      closeCard()
      return
    }
    var draft = state.drafting
    var detail = detailOf(state.anchor)
    if (draft.existing) {
      state.annotations = state.annotations.map(function (ann) {
        return ann.id === draft.id
          ? Object.assign({}, ann, detail, { comment: text })
          : ann
      })
    } else {
      state.annotations = state.annotations.concat([
        Object.assign({ id: draft.id, comment: text, createdAt: Date.now() }, detail),
      ])
    }
    liveElements.set(draft.id, state.anchor)
    save()
    var ship = state.sendOnCommit
    state.sendOnCommit = false
    closeCard()
    renderPins()
    post('changed', { annotations: state.annotations })
    if (ship) post('send', { annotations: state.annotations })
  }

  // ------------------------------------------------------------------ picking

  function pick(event) {
    if (state.busy) return
    var el = elementAt(event.clientX, event.clientY)
    if (!el) {
      // Backdrop click while writing: treat it as cancel.
      if (state.mode === 'writing' && card) {
        event.preventDefault()
        event.stopPropagation()
        closeCard()
      }
      return
    }
    event.preventDefault()
    event.stopPropagation()
    state.selected = el
    state.hover = null
    state.mode = 'writing'
    post('mode', { mode: state.mode, count: state.annotations.length })
    // Codex parity: ⌘/Ctrl-click means "write it and ship it".
    state.sendOnCommit = Boolean(event.metaKey || event.ctrlKey)
    render()
    openCard({ id: 'a' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6), detail: detailOf(el), comment: '' }, el)
  }

  function onMove(event) {
    if (state.mode !== 'picking') return
    var el = elementAt(event.clientX, event.clientY)
    if (!el) return
    if (el === state.hover) return
    state.hover = el
    renderFrame()
  }

  function setMode(mode) {
    state.mode = mode
    if (mode !== 'writing') {
      state.selected = null
      state.hover = null
      closeCard()
    }
    render()
    post('mode', { mode: state.mode, count: state.annotations.length })
  }

  function post(type, payload) {
    var target = window.__DSH_ANNO__ && window.__DSH_ANNO__.parentOrigin
    if (!target) return
    try {
      parent.postMessage(
        Object.assign(
          { source: CHANNEL, type: type, url: window.__dshAnnoState ? window.__dshAnnoState().url : location.href, viewport: { w: window.innerWidth, h: window.innerHeight } },
          payload || {}
        ),
        target
      )
    } catch (e) {
      /* the panel is gone */
    }
  }

  window.addEventListener('message', function (event) {
    // Source alone is not enough: any window that can reach this frame could
    // claim it. The message must also come from the harness origin.
    if (event.source !== parent || event.origin !== (window.__DSH_ANNO__ && window.__DSH_ANNO__.parentOrigin)) return
    var data = event.data
    if (!data || data.source !== HOST) return
    if (data.type === 'busy') { state.busy = data.value; return }
    if (data.type === 'lang') { setLang(data.lang); return }
    if (data.type === 'restore') {
      state.annotations = Array.isArray(data.annotations) ? data.annotations : []
      liveElements.clear()
      save(); renderPins()
      if (data.draft && data.draft.comment) {
        var target = query(data.draft.detail.selector)
        if (target) { state.mode = 'writing'; openCard(data.draft, target) }
      }
      return
    }
    if (data.type === 'navigate') { history.go(data.delta); return }
    if (data.type === 'reload') { location.reload(); return }
    if (data.type === 'set-mode') setMode(data.mode)
    // The panel cannot always know whether a card is open; let the overlay —
    // which owns the mode — decide what "toggle" means right now.
    if (data.type === 'toggle-mode') setMode(state.mode === 'idle' ? 'picking' : 'idle')
    else if (data.type === 'focus') {
      var ann = state.annotations.filter(function (a) {
        return a.id === data.id
      })[0]
      var el = ann ? elementFor(ann) : null
      if (!el) post('missing', { id: data.id })
      if (el) {
        el.scrollIntoView({ block: 'center', behavior: 'smooth' })
        state.selected = el
        renderFrame()
      }
    } else if (data.type === 'undo') {
      if (undo) { state.annotations.push(undo); undo = null; save(); renderPins(); post('changed', { annotations: state.annotations }) }
    } else if (data.type === 'remove') {
      undo = state.annotations.find(function (a) { return a.id === data.id }) || null
      state.annotations = state.annotations.filter(function (a) {
        return a.id !== data.id
      })
      save()
      renderPins()
      post('changed', { annotations: state.annotations })
    } else if (data.type === 'clear') {
      setMode('idle')
      var removed = new Set(data.ids || state.annotations.map(function (a) { return a.id }))
      state.annotations = state.annotations.filter(function (a) { return !removed.has(a.id) })
      save()
      renderPins()
      post('changed', { annotations: state.annotations })
    } else if (data.type === 'ping') {
      post('ready', { annotations: state.annotations, path: location.pathname })
    }
  }, false)

  capture.addEventListener('mousemove', onMove, true)
  capture.addEventListener('click', pick, true)
  capture.addEventListener('contextmenu', function (event) {
    event.preventDefault()
    setMode('idle')
  }, true)
  window.addEventListener('keydown', function (event) {
    if (event.key === 'Escape' && !card) setMode('idle')
  }, true)
  /** Re-anchor stored annotations to their live elements: layout can shift
   *  under a pin (content growing above it, a route change, a resize). */
  function resyncAnchors() {
    var changed = false
    state.annotations = state.annotations.map(function (ann) {
      var el = elementFor(ann)
      if (!el || !el.isConnected) return ann
      var rect = el.getBoundingClientRect()
      var doc = {
        x: Math.round(rect.x + window.scrollX),
        y: Math.round(rect.y + window.scrollY),
        w: Math.round(rect.width),
        h: Math.round(rect.height),
      }
      if (ann.doc && Math.abs(ann.doc.x - doc.x) < 1 && Math.abs(ann.doc.y - doc.y) < 1) return ann
      changed = true
      return Object.assign({}, ann, { doc: doc })
    })
    if (changed) save()
  }

  // Capture phase: scroll events from inner containers do not bubble, but they
  // are delivered to window listeners registered for capture.
  var frameQueued = false
  function onViewportChange() {
    if (frameQueued) return
    frameQueued = true
    requestAnimationFrame(function () {
      frameQueued = false
      renderFrame()
      positionPins()
    })
  }
  window.addEventListener('scroll', onViewportChange, true)
  document.addEventListener('scroll', onViewportChange, true)
  window.addEventListener('resize', function () {
    resyncAnchors()
    renderFrame()
    renderPins()
  })

  function changePage() {
    var next = location.pathname + location.search + location.hash
    if (next === currentPage) return
    save()
    closeCard(true)
    currentPage = next
    state.annotations = load()
    state.hover = null
    state.selected = null
    liveElements.clear()
    undo = null
    setMode('idle')
    post('ready', { annotations: state.annotations })
  }
  ;['pushState', 'replaceState'].forEach(function (method) {
    var original = history[method]
    history[method] = function () {
      var result = original.apply(this, arguments)
      changePage()
      return result
    }
  })
  window.addEventListener('popstate', changePage)
  window.addEventListener('hashchange', changePage)

  // Picking captures clicks, but wheel scrolling must still reach the real
  // nested scroller under the pointer rather than the fixed overlay surface.
  capture.addEventListener('wheel', function (event) {
    var node = elementAt(event.clientX, event.clientY)
    var scale = event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? innerHeight : 1
    var dy = event.deltaY * scale, dx = event.deltaX * scale
    while (node && node !== document.documentElement) {
      var style = getComputedStyle(node)
      var canY = /(auto|scroll)/.test(style.overflowY) && (dy < 0 ? node.scrollTop > 0 : node.scrollTop + node.clientHeight < node.scrollHeight)
      var canX = /(auto|scroll)/.test(style.overflowX) && (dx < 0 ? node.scrollLeft > 0 : node.scrollLeft + node.clientWidth < node.scrollWidth)
      if ((dy && canY) || (dx && canX)) {
        node.scrollBy(dx, dy); event.preventDefault(); return
      }
      node = node.parentElement
    }
    window.scrollBy(dx, dy)
    event.preventDefault()
  }, { passive: false })

  // Layout/transform animations do not necessarily emit scroll or resize.
  // Keep only the live markers in sync; never rebuild DOM or write storage in
  // this loop. Browsers pause rAF while the preview is in the background.
  function trackAnchors() {
    if (state.annotations.length || card) positionPins()
    if (card) anchorCard()
    requestAnimationFrame(trackAnchors)
  }
  requestAnimationFrame(trackAnchors)
  state.annotations = load()
  if (document.body) mount()
  else document.addEventListener('DOMContentLoaded', mount)
  post('ready', { annotations: state.annotations, path: location.pathname })
})()

})()
