/**
 * Build what DSH loads.
 *
 *   lib/index.js   — host half: ESM, copied verbatim from src/host.js
 *   lib/shim.js    — injected into previewed pages (read by the host half)
 *   lib/overlay.js — injected into previewed pages (read by the host half)
 *   lib/client.js  — client half: a browser module bundle
 *
 * The web client's module loader calls a registered factory with a `require`
 * that resolves the shared singletons (React), then reads `apply`/`inject` off
 * the module exports. The only hand-written part is the registration wrapper;
 * the format itself is the documented one
 * (docs/subsystems/client-modules.md in the harness repository).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const read = (...parts) => readFileSync(join(root, ...parts), 'utf8')

mkdirSync(join(root, 'lib', 'types', 'client'), { recursive: true })

// The message catalog is a plain script, not a module: both consumers load it
// by concatenation rather than through a loader. It is prepended inside the
// client factory and wrapped together with the overlay in one IIFE, so neither
// leaks a global into the harness page or the previewed page.
const i18nSource = read('src', 'i18n.js')

// ---- host half -------------------------------------------------------------
// The host reads shim.js and overlay.js at runtime, so they ship as their own
// files (keeps them readable and patchable without a rebuild).
writeFileSync(join(root, 'lib', 'index.js'), read('src', 'host.js'))
writeFileSync(join(root, 'lib', 'shim.js'), read('src', 'shim.js'))
writeFileSync(
  join(root, 'lib', 'overlay.js'),
  [
    '// Generated by build.mjs — edit src/overlay.js and src/i18n.js instead.',
    ';(function () {',
    i18nSource,
    read('src', 'overlay.js'),
    '})()',
    '',
  ].join('\n')
)

// ---- client half -----------------------------------------------------------
const clientSource = read('src', 'client.js')

const bundle = [
  '// Generated by build.mjs — edit src/client.js instead.',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  '    const React = require("react");',
  i18nSource,
  clientSource,
  '    exports.apply = apply;',
  '    if (typeof inject !== "undefined") exports.inject = inject;',
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

writeFileSync(join(root, 'lib', 'client.js'), bundle)

// ---- minimal type faces ----------------------------------------------------
writeFileSync(
  join(root, 'lib', 'types', 'index.d.ts'),
  'export declare const name: string\nexport declare const inject: string[]\nexport declare function apply(ctx: unknown, config?: unknown): void\n'
)
writeFileSync(
  join(root, 'lib', 'types', 'client', 'index.d.ts'),
  'export declare const inject: string[]\nexport declare function apply(ctx: unknown): void\n'
)

// `npm pack` / `npm publish` run this as `prepack` and parse stdout (for
// example `npm pack --dry-run --json`), so stay quiet on that entry point.
if (process.env.npm_lifecycle_event !== 'prepack') {
  console.log(`built ${pkg.name}: lib/index.js, lib/shim.js, lib/overlay.js, lib/client.js, lib/types/*`)
}
