/**
 * Build the two faces DSH loads.
 *
 *   lib/index.js  — host half: ESM, copied verbatim from src/host.js
 *   lib/client.js — client half: a browser module bundle
 *
 * The web client's module loader calls a registered factory with a `require`
 * that resolves the shared singletons (React), then reads `apply`/`inject` off
 * the module exports. The only hand-written part is the registration wrapper;
 * the format itself is the documented one
 * (docs/subsystems/client-modules.md in the harness repository).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const read = (...parts) => readFileSync(join(root, ...parts), 'utf8')

mkdirSync(join(root, 'lib', 'types', 'client'), { recursive: true })

// ---- host half -------------------------------------------------------------
writeFileSync(join(root, 'lib', 'index.js'), read('src', 'host.js'))

// ---- client half -----------------------------------------------------------
const clientSource = read('src', 'client.js')
const overlaySource = read('src', 'overlay.js')

const bundle = [
  '// Generated by build.mjs — edit src/client.js and src/overlay.js instead.',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} };',
  '    const exports = module.exports;',
  '    const React = require("react");',
  `    const OVERLAY_SRC = ${JSON.stringify(overlaySource)};`,
  clientSource,
  '    exports.apply = apply;',
  '    if (typeof inject !== "undefined") exports.inject = inject;',
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

writeFileSync(join(root, 'lib', 'client.js'), bundle)

// ---- minimal type faces ----------------------------------------------------
writeFileSync(
  join(root, 'lib', 'types', 'index.d.ts'),
  'export declare const name: string\nexport declare const inject: string[]\nexport declare function apply(ctx: unknown, config?: unknown): void\n'
)
writeFileSync(
  join(root, 'lib', 'types', 'client', 'index.d.ts'),
  'export declare const inject: string[]\nexport declare function apply(ctx: unknown): void\n'
)

console.log(`built ${pkg.name}: lib/index.js, lib/client.js, lib/types/*`)
