/**
 * One command for the plugin development loop.
 *
 * Creates (or refreshes) a dedicated DSH profile that loads both packages from
 * this checkout and previews the bundled fixture, boots the harness on its own
 * port, and prints the tokenised URL. Nothing here touches your daily profile.
 *
 *   node scripts/dev.mjs
 *   node scripts/dev.mjs --base /demo/ --app-port 5199 --port 3099
 *   node scripts/dev.mjs --open             # open the GUI in a browser
 *
 * Changing the client half only needs a page refresh; changing the host half or
 * the bridge needs this harness restarted (Ctrl-C, run again).
 */
import { spawn, spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = dirname(dirname(fileURLToPath(import.meta.url)))
const flag = (name, fallback) => {
  const index = process.argv.indexOf(`--${name}`)
  if (index < 0) return fallback
  const next = process.argv[index + 1]
  return !next || next.startsWith('--') ? true : next
}

const profile = String(flag('profile', 'dsh-annotate-dev'))
const harnessPort = Number(flag('port', 3099))
const appPort = Number(flag('app-port', 5180))
const base = (() => {
  const raw = String(flag('base', '/app/')).trim()
  if (!raw || raw === '/') return '/'
  const withLead = raw.startsWith('/') ? raw : `/${raw}`
  return withLead.endsWith('/') ? withLead : `${withLead}/`
})()
const wantOpen = Boolean(flag('open', false))
const prefix = base === '/' ? '/' : base.replace(/\/$/, '')

const profileDir = join(homedir(), '.dsh', 'profiles', profile)
const fixture = join(repo, 'examples', 'demo-app', 'server.mjs')
const command = `node ${fixture} --port ${appPort} --base ${base}`

// ---------------------------------------------------------------- profile

function seedProfile() {
  mkdirSync(profileDir, { recursive: true })
  const template = ['web', 'bridgecheck']
    .map((name) => join(homedir(), '.dsh', 'profiles', name))
    .find((dir) => existsSync(join(dir, 'cordis.yml')))

  if (template) {
    for (const file of ['cordis.yml', 'pnpm-workspace.yaml']) {
      if (existsSync(join(template, file))) copyFileSync(join(template, file), join(profileDir, file))
    }
    if (existsSync(join(template, '.dsh-module-fallback'))) {
      rmSync(join(profileDir, '.dsh-module-fallback'), { recursive: true, force: true })
      spawnSync('cp', ['-R', join(template, '.dsh-module-fallback'), join(profileDir, '.dsh-module-fallback')])
    }
  } else {
    writeFileSync(join(profileDir, 'cordis.yml'), '# dsh profile root — patches compose the tree\n[]\n')
    writeFileSync(join(profileDir, 'pnpm-workspace.yaml'), 'packages:\n  - .\n\nnodeLinker: hoisted\nautoInstallPeers: false\n')
  }

  writeFileSync(
    join(profileDir, 'package.json'),
    JSON.stringify(
      {
        name: `dsh-profile-${profile}`,
        private: true,
        dsh: { profile: { bundles: ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app'], patchReload: 'live' } },
        dependencies: {
          'dsh-annotate': `link:${join(repo, 'packages', 'dsh-annotate')}`,
          'dsh-app-bridge': `link:${join(repo, 'packages', 'dsh-app-bridge')}`,
        },
      },
      null,
      2
    ) + '\n'
  )

  const patch = `# Generated by scripts/dev.mjs — the plugin development sandbox.
# Previewed project: examples/demo-app (${command})
- id: webserver
  config:
    host: 127.0.0.1
    port: ${harnessPort}
    compression: none
    compressionLevel: 1
    compressionThresholdBytes: 1024
- insert:
    # Same-origin bridge: the fixture appears on the harness origin under ${prefix}
    - name: dsh-app-bridge
      config:
        target: http://127.0.0.1:${appPort}
        prefix: ${prefix}
    # Annotation tab: starts the fixture itself and previews ${base}
    - name: dsh-annotate
      config:
        command: ${JSON.stringify(command)}
        port: ${appPort}
        base: ${JSON.stringify(base)}
`
  writeFileSync(join(profileDir, 'cordis.patch.yml'), patch)

  const install = spawnSync('npx', ['--yes', 'pnpm@10', 'install'], {
    cwd: profileDir,
    stdio: 'pipe',
    encoding: 'utf8',
  })
  if (install.status !== 0) {
    console.error(install.stdout || '', install.stderr || '')
    throw new Error('pnpm install failed in ' + profileDir)
  }
}

// ---------------------------------------------------------------- harness

console.log(`profile      ${profileDir}`)
console.log(`previewed    ${command}`)
console.log(`bridge       http://127.0.0.1:${harnessPort}${base}  ->  http://127.0.0.1:${appPort}${base}`)
seedProfile()

const child = spawn('dsh', ['--profile', profile, '--no-open'], {
  stdio: ['ignore', 'pipe', 'pipe'],
  env: process.env,
})

let url = null
const forward = (chunk) => {
  const text = String(chunk)
  process.stdout.write(text.replace(/^/gm, '  │ ').replace(/^ {2}│ $/gm, ''))
  const match = text.match(/https?:\/\/[^\s]*token=[A-Za-z0-9_-]+/)
  if (match && !url) {
    url = match[0]
    console.log('\n' + '─'.repeat(72))
    console.log('  harness ready:  ' + url)
    console.log('  open a conversation, press ⌘⇧B, the fixture starts itself')
    console.log('  client-half edits: npm run build then refresh · host-half: restart this script')
    console.log('─'.repeat(72) + '\n')
    if (wantOpen) spawn('open', [url], { stdio: 'ignore', detached: true }).unref()
  }
}
child.stdout.on('data', forward)
child.stderr.on('data', forward)

const shutdown = (signal) => {
  console.log(`\n· ${signal} — stopping harness`)
  child.kill('SIGTERM')
  setTimeout(() => process.exit(0), 300)
}
process.on('SIGINT', () => shutdown('SIGINT'))
process.on('SIGTERM', () => shutdown('SIGTERM'))
child.on('exit', (code) => {
  console.log(`· harness exited (${code})`)
  process.exit(code ?? 0)
})
