/**
 * One command for the plugin development loop.
 *
 * Starts the bundled fixture (a plain local web server) and a dedicated DSH
 * profile that loads this checkout with **no configuration**, then prints the
 * tokenised URL. Nothing here touches your daily profile.
 *
 *   node scripts/dev.mjs
 *   node scripts/dev.mjs --app-port 5199 --port 3099
 *   node scripts/dev.mjs --open             # open the GUI in a browser
 *
 * Changing the client half only needs a page refresh; changing the host half or
 * the bridge needs this harness restarted (Ctrl-C, run again).
 */
import { spawn, spawnSync } from 'node:child_process'
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = dirname(dirname(fileURLToPath(import.meta.url)))
const flag = (name, fallback) => {
  const index = process.argv.indexOf(`--${name}`)
  if (index < 0) return fallback
  const next = process.argv[index + 1]
  return !next || next.startsWith('--') ? true : next
}

const profile = String(flag('profile', 'dsh-annotate-dev'))
const harnessPort = Number(flag('port', 3099))
const appPort = Number(flag('app-port', 5180))
const base = (() => {
  const raw = String(flag('base', '/')).trim()
  if (!raw || raw === '/') return '/'
  const withLead = raw.startsWith('/') ? raw : `/${raw}`
  return withLead.endsWith('/') ? withLead : `${withLead}/`
})()
const wantOpen = Boolean(flag('open', false))
const prefix = base === '/' ? '/' : base.replace(/\/$/, '')

const profileDir = join(homedir(), '.dsh', 'profiles', profile)
const fixture = join(repo, 'examples', 'demo-app', 'server.mjs')
const command = `node ${fixture} --port ${appPort} --base ${base}`

// ---------------------------------------------------------------- profile

function seedProfile() {
  mkdirSync(profileDir, { recursive: true })
  const template = ['web', 'bridgecheck']
    .map((name) => join(homedir(), '.dsh', 'profiles', name))
    .find((dir) => existsSync(join(dir, 'cordis.yml')))

  if (template) {
    for (const file of ['cordis.yml', 'pnpm-workspace.yaml']) {
      if (existsSync(join(template, file))) copyFileSync(join(template, file), join(profileDir, file))
    }
    if (existsSync(join(template, '.dsh-module-fallback'))) {
      rmSync(join(profileDir, '.dsh-module-fallback'), { recursive: true, force: true })
      cpSync(join(template, '.dsh-module-fallback'), join(profileDir, '.dsh-module-fallback'), { recursive: true })
    }
  } else {
    writeFileSync(join(profileDir, 'cordis.yml'), '# dsh profile root — patches compose the tree\n[]\n')
    writeFileSync(join(profileDir, 'pnpm-workspace.yaml'), 'packages:\n  - .\n\nnodeLinker: hoisted\nautoInstallPeers: false\n')
  }

  writeFileSync(
    join(profileDir, 'package.json'),
    JSON.stringify(
      {
        name: `dsh-profile-${profile}`,
        private: true,
        dsh: { profile: { bundles: ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app'], patchReload: 'live' } },
        dependencies: {
          'dsh-annotate': `link:${join(repo, 'packages', 'dsh-annotate')}`,
        },
      },
      null,
      2
    ) + '\n'
  )

  const patch = `# Generated by scripts/dev.mjs — the plugin development sandbox.
# Previewed project: examples/demo-app (${command})
- id: webserver
  config:
    host: 127.0.0.1
    port: ${harnessPort}
    compression: none
    compressionLevel: 1
    compressionThresholdBytes: 1024
- insert:
    # Zero configuration on purpose: the tab discovers whatever is running and
    # opens it in its own loopback preview origin. This mirrors what a user
    # installs; dsh-app-bridge is not involved.
    - name: dsh-annotate
`
  writeFileSync(join(profileDir, 'cordis.patch.yml'), patch)

  const install = spawnSync('npx', ['--yes', 'pnpm@10', 'install'], {
    cwd: profileDir,
    stdio: 'pipe',
    encoding: 'utf8',
  })
  if (install.status !== 0) {
    console.error(install.stdout || '', install.stderr || '')
    throw new Error('pnpm install failed in ' + profileDir)
  }
}

// ---------------------------------------------------------------- harness

console.log(`profile      ${profileDir}`)
console.log(`fixture      ${command}`)
seedProfile()

// The fixture is started here, like any dev server you would already have
// running: the plugin's job is to find it, not to own it.
const fixtureProc = spawn('node', [fixture, '--port', String(appPort), '--base', base], {
  stdio: ['ignore', 'pipe', 'pipe'],
})
fixtureProc.stdout.on('data', (chunk) => process.stdout.write('  │ ' + chunk))
fixtureProc.stderr.on('data', (chunk) => process.stdout.write('  │ ' + chunk))

const child = spawn('dsh', ['--profile', profile, '--no-open'], {
  stdio: ['ignore', 'pipe', 'pipe'],
  env: process.env,
})

let url = null
const forward = (chunk) => {
  const text = String(chunk)
  process.stdout.write(text.replace(/^/gm, '  │ ').replace(/^ {2}│ $/gm, ''))
  const match = text.match(/https?:\/\/[^\s]*token=[A-Za-z0-9_-]+/)
  if (match && !url) {
    url = match[0]
    console.log('\n' + '─'.repeat(72))
    console.log('  harness ready:  ' + url)
    console.log('  open a conversation, press ⌘⇧B — the fixture is listed, click it')
    console.log('  client-half edits: npm run build then refresh · host-half: restart this script')
    console.log('─'.repeat(72) + '\n')
    if (wantOpen) openInBrowser(url)
  }
}
child.stdout.on('data', forward)
child.stderr.on('data', forward)

/** `--open` is a convenience, not a feature: fail quietly where it cannot work. */
function openInBrowser(url) {
  const [command, args] =
    process.platform === 'darwin' ? ['open', [url]]
      : process.platform === 'win32' ? ['cmd', ['/c', 'start', '', url]]
        : ['xdg-open', [url]]
  try {
    spawn(command, args, { stdio: 'ignore', detached: true }).unref()
  } catch (error) {
    console.log(`· could not open a browser (${String(error.message)}): ${url}`)
  }
}

const shutdown = (signal) => {
  console.log(`\n· ${signal} — stopping harness and fixture`)
  child.kill('SIGTERM')
  fixtureProc.kill('SIGTERM')
  setTimeout(() => process.exit(0), 300)
}
process.on('SIGINT', () => shutdown('SIGINT'))
process.on('SIGTERM', () => shutdown('SIGTERM'))
child.on('exit', (code) => {
  console.log(`· harness exited (${code})`)
  fixtureProc.kill('SIGTERM')
  process.exit(code ?? 0)
})
